# This is a basic workflow to help you get started with Actions
name: Test Runner

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches:
      - master
  #schedule:
    # At 04:00 on Monday. → At 19:00 on Sunday.
  #  - cron:  '0 19 * * 0'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "scrapy-runner"
  test-runner:
    # The type of runner that the job will run on
    runs-on: self-hosted
    timeout-minutes: 20

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Run scrapy
      - name: test
        shell: bash
        run: |
          env
          ls -al
